import {
  BarChart2,
  TrendingUp,
  Users,
  Settings,
  DollarSign,
  ShoppingCart,
  Target,
  Zap,
  Heart,
  Shield,
  Truck,
  Package,
  Briefcase,
  GraduationCap,
  Building,
  Clock,
  Lightbulb,
  Award,
  Activity,
  PieChart,
  LineChart,
  Wallet,
  CreditCard,
  Headphones,
  Megaphone,
  Globe,
  Wrench,
  Layers,
  type LucideIcon,
} from "lucide-react";

export const domainIconMap: Record<string, LucideIcon> = {
  BarChart2,
  TrendingUp,
  Users,
  Settings,
  DollarSign,
  ShoppingCart,
  Target,
  Zap,
  Heart,
  Shield,
  Truck,
  Package,
  Briefcase,
  GraduationCap,
  Building,
  Clock,
  Lightbulb,
  Award,
  Activity,
  PieChart,
  LineChart,
  Wallet,
  CreditCard,
  Headphones,
  Megaphone,
  Globe,
  Wrench,
  Layers,
};

export const ICON_OPTIONS = [
  { value: "BarChart2", label: "Bar Chart" },
  { value: "TrendingUp", label: "Trending Up" },
  { value: "Users", label: "Users" },
  { value: "Settings", label: "Settings" },
  { value: "DollarSign", label: "Dollar Sign" },
  { value: "ShoppingCart", label: "Shopping Cart" },
  { value: "Target", label: "Target" },
  { value: "Zap", label: "Zap" },
  { value: "Heart", label: "Heart" },
  { value: "Shield", label: "Shield" },
  { value: "Truck", label: "Truck" },
  { value: "Package", label: "Package" },
  { value: "Briefcase", label: "Briefcase" },
  { value: "GraduationCap", label: "Graduation Cap" },
  { value: "Building", label: "Building" },
  { value: "Clock", label: "Clock" },
  { value: "Lightbulb", label: "Lightbulb" },
  { value: "Award", label: "Award" },
  { value: "Activity", label: "Activity" },
  { value: "PieChart", label: "Pie Chart" },
  { value: "LineChart", label: "Line Chart" },
  { value: "Wallet", label: "Wallet" },
  { value: "CreditCard", label: "Credit Card" },
  { value: "Headphones", label: "Headphones" },
  { value: "Megaphone", label: "Megaphone" },
  { value: "Globe", label: "Globe" },
  { value: "Wrench", label: "Wrench" },
  { value: "Layers", label: "Layers" },
];

export const DEFAULT_ICON = "BarChart2";
